# Generated by Django 2.1.5 on 2019-01-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoggedInUser', models.CharField(max_length=20)),
                ('LoggedInDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReconUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReconTitle', models.CharField(max_length=100)),
                ('RespPers', models.CharField(max_length=30)),
                ('ReconTotalCount', models.IntegerField()),
                ('ReconExecutedCount', models.IntegerField()),
                ('ReconDate', models.DateField()),
                ('UpdateDate', models.DateField()),
            ],
        ),
    ]
