# Generated by Django 2.1.5 on 2019-01-29 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconupdate',
            name='UserEmailId',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reconupdate',
            name='UserId',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
