# Generated by Django 2.1.5 on 2019-01-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDApp', '0002_auto_20190129_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconupdate',
            name='UserEmailId',
        ),
    ]
