# Generated by Django 2.1.5 on 2019-05-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDApp', '0002_auto_20190502_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newreconupdate',
            name='ReconDateTime',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='newreconupdate',
            name='ReconExecutedCount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='newreconupdate',
            name='ReconTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newreconupdate',
            name='ReconTotalCount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='newreconupdate',
            name='ReconType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='newreconupdate',
            name='ReconUser',
            field=models.CharField(default='', max_length=30),
        ),
    ]
