# Generated by Django 2.1.5 on 2019-01-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDApp', '0003_remove_reconupdate_useremailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconupdate',
            name='UpdateDate',
            field=models.CharField(max_length=30),
        ),
    ]
